export const boldWords = [
  "full-stack developer",
  "developer",
  "web services",
  "React.js",
  "Next.js",
  "Node.js",
  "UI/UX-centered approach",
  "high-quality services",
  "features",
  "user experience",
  "value",
  "풀스택 개발자",
  "웹 서비스",
  "완성도 높은 서비스",
  "기능",
  "사용자 경험의 가치",
];
